### ISSUE TITLE
[feature] Hardcoded typings

### ISSUE THREAD

**Issue by vurvdev** [Derpius/nanosworld-vscode#4]
**Is your feature request related to a problem? Please describe.**
There's no concept of structs for nanos types, so for example Client.Trace just returns a ``table``. Additionally, metamethods of classes aren't handled right now (Like Vector - Vector)

**Describe the solution you'd like**
Operator support could be hardcoded for the nanos-utils structs here: https://github.com/nanos-world/nanos-world-lua-lib/blob/master/Classes

And specific functions like Client.Trace could be overridden to return the more specific table return: 
```lua
---@class TraceResult
---@field Success boolean
---@field Location Vector
---@field Normal Vector
---@field Entity Actor?
---@field BoneName string
---@field ActorName string
---@field SurfaceType SurfaceType
```

**Describe alternatives you've considered**
Could maybe PR some sort of "operator" schema to the https://github.com/nanos-world/api, not sure how this would go though

**Additional context**
This is painful
![image](https://user-images.githubusercontent.com/56230599/184461992-1ee3c179-ad0a-4fd8-8fee-6f5fae49cf88.png)

**Comment by Derpius** [comment]
Operators can be approximated by assuming every `Structs` class has all operators except bitwise defined  

Although things like TraceResult should really be a struct in the json, which would make the above invalid

**Comment by Derpius** [comment]
Both operators and typed tables have been added to the schema
