### ISSUE TITLE
[bug] Union types not properly generating

### ISSUE THREAD

**Issue by vurvdev** [Derpius/nanosworld-vscode#6]
**Describe the bug**
Union types (e.g. ``Prop|Pickable``) are generated by just concatenating the type names for some reason.

**Expected behaviour**
Should just leave them as is, considering emmylua / sumneko lua supports union types with the same syntax.c

**Screenshots**
Below should be ``string|table``
![image](https://user-images.githubusercontent.com/56230599/184463915-80543a06-8219-4d3b-b5aa-a9347ab90582.png)

**Comment by Derpius** [comment]
yeah that's gonna be an issue with the ComplexType tostring

**Comment by Derpius** [comment]
Fixed in 18aa8458c5f49b2eb3c7aba8964dbdbba473823d
